### ISSUE TITLE
Some regressions in plugin

### ISSUE THREAD

**Issue by le717** [gabceb/jquery-browser-plugin#46]
I'm opening this not only for reporting, but also to document what I am seeing. I will update this until I've uncovered everything.

c91197027f272f83a9cc046db7915e113358d7f2 has broken a number of tests and thus functionality:
- Browser should be Safari on Mac
- Browser should be Safari on iPad
- Browser should be Safari on iPhone
- Browser name should be Android
- There are three more broken tests right now, but they are not directly related to this, and are out of scope for the issue at hand.

Through manual testing, I've found `browser.safari` is returning `undefined`, and `browser.name` is returning `"version"` with some UAs.

The script changes in that commit, however, were only applied to the script in the `test/src` folder. These issues do not reproduce with the script under `dist/`.

I am partly to blame here, as some of the changes made were mine (see the [`le717-safari-version`](https://github.com/gabceb/jquery-browser-plugin/tree/le717-safari-version) branch and #35).
### TODO
- [x] Make `browser.safari` work again
- [x] Research what UAs are breaking `browser.name` and fix that
- [x] Ensure #35 is still fixed
- [x] Code review (#49)
